name: Build and Package Extension

on:
    push:
        branches: [main]
        tags:
            - "v*"
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write # needed to create tags and releases
    packages: read

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            artifact-names: ${{ steps.set-artifacts.outputs.names }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Create extension package
              run: npm run package

            - name: Upload extension ZIP
              uses: actions/upload-artifact@v4
              with:
                  name: alt-text-auto-fill-extension
                  path: dist/alt-text-auto-fill.zip
                  if-no-files-found: error

            - name: Upload unpacked extension
              uses: actions/upload-artifact@v4
              with:
                  name: alt-text-auto-fill-unpacked
                  path: dist/unpacked/
                  if-no-files-found: error

            - name: Set artifact names output
              id: set-artifacts
              run: |
                  echo "::set-output name=names::alt-text-auto-fill-extension,alt-text-auto-fill-unpacked"

            # Create release if this is a tag push (preserve your previous behavior)
            - name: Create Release (on tag push)
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      dist/alt-text-auto-fill.zip
                      dist/alt-text-auto-fill-source.zip
                  draft: false
                  prerelease: false
                  body: |
                      ## Alt Text Auto-Fill Chrome Extension
                      By Software for Progress Foundation

                      ### Installation Instructions
                      1. Download `alt-text-auto-fill.zip`
                      2. Extract the ZIP file
                      3. Open Chrome and go to `chrome://extensions/`
                      4. Enable "Developer mode"
                      5. Click "Load unpacked" and select the extracted folder

                      ### What's New
                      See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Checkout so we can tag
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: true

            - name: Download built extension zip
              uses: actions/download-artifact@v4
              with:
                  name: alt-text-auto-fill-extension
                  path: ./artifacts/extension

            - name: Download unpacked artifact
              uses: actions/download-artifact@v4
              with:
                  name: alt-text-auto-fill-unpacked
                  path: ./artifacts/unpacked

            - name: Determine tag name
              id: tag
              run: |
                  set -e
                  # Try to use package.json version if available
                  if [ -f package.json ]; then
                    pkg_version=$(node -pe "require('./package.json').version" 2>/dev/null || echo "")
                  else
                    pkg_version=""
                  fi

                  if [ -n "$pkg_version" ]; then
                    # Ensure tag starts with v
                    if [[ "$pkg_version" = v* ]]; then
                      TAG="$pkg_version"
                    else
                      TAG="v$pkg_version"
                    fi
                  else
                    DATE=$(date +'%Y.%m.%d')
                    SHORT=${GITHUB_SHA::7}
                    TAG="v${DATE}-${SHORT}"
                  fi

                  echo "Computed tag: $TAG"
                  echo "::set-output name=tag::$TAG"

            - name: Configure git user
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Create tag if it does not exist and push
              env:
                  TAG: ${{ steps.tag.outputs.tag }}
              run: |
                  set -e
                  # Check remote for tag
                  if git ls-remote --tags origin refs/tags/"$TAG" | grep -q "$TAG"; then
                    echo "Tag $TAG already exists on remote. Skipping tag creation."
                  else
                    echo "Creating tag $TAG"
                    git tag -a "$TAG" -m "Release $TAG"
                    git push origin "refs/tags/$TAG"
                    echo "Pushed tag $TAG"
                  fi

            - name: Create GitHub Release and upload assets
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.tag.outputs.tag }}
                  name: Release ${{ steps.tag.outputs.tag }}
                  body: |
                      ## Alt Text Auto-Fill Chrome Extension
                      By Software for Progress Foundation

                      ### Installation Instructions
                      1. Download `alt-text-auto-fill.zip`
                      2. Extract the ZIP file
                      3. Open Chrome and go to `chrome://extensions/`
                      4. Enable "Developer mode"
                      5. Click "Load unpacked" and select the extracted folder

                      ### What's New
                      See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
                  files: |
                      ./artifacts/extension/dist/alt-text-auto-fill.zip
                      ./artifacts/unpacked/**

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Validate manifest
              run: npm run validate-manifest
