name: Build and Package Extension

on:
    push:
        branches: [main]
        tags:
            - "v*"
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write
    packages: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build extension
              run: npm run build

            - name: Check build output
              run: |
                  echo "Build complete. Checking file sizes:"
                  ls -lh dist/
                  echo "---"
                  echo "Total dist size:"
                  du -sh dist/

            - name: Create extension package
              run: npm run package

            - name: Upload extension ZIP
              uses: actions/upload-artifact@v4
              with:
                  name: alt-text-auto-fill-extension
                  path: alt-text-auto-fill.zip
                  if-no-files-found: error

            - name: Upload unpacked extension
              uses: actions/upload-artifact@v4
              with:
                  name: alt-text-auto-fill-unpacked
                  path: dist/
                  if-no-files-found: error

            # Create release if this is a tag push
            - name: Create Release (on tag push)
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  files: alt-text-auto-fill.zip
                  draft: false
                  prerelease: false
                  generate_release_notes: true
                  body: |
                      ## Alt Text Auto-Fill Chrome Extension v${{ github.ref_name }}
                      By Software for Progress Foundation

                      ### 🚀 Installation
                      1. Download `alt-text-auto-fill.zip`
                      2. Extract to a folder
                      3. Open `chrome://extensions/`
                      4. Enable "Developer mode"
                      5. Click "Load unpacked" and select the folder

                      ### ✨ Features
                      - AI-powered object detection
                      - Describes image contents accurately
                      - Works with cross-origin images
                      - WebGL acceleration
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    auto-release:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download extension ZIP
              uses: actions/download-artifact@v4
              with:
                  name: alt-text-auto-fill-extension

            - name: Get version from package.json
              id: version
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  echo "version=v${VERSION}" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  tag: ${{ steps.version.outputs.version }}
                  name: Release ${{ steps.version.outputs.version }}
                  artifacts: "alt-text-auto-fill.zip"
                  allowUpdates: true
                  makeLatest: true
                  body: |
                      ## Alt Text Auto-Fill Chrome Extension
                      Version ${{ steps.version.outputs.version }}

                      ### Installation
                      1. Download the ZIP file below
                      2. Extract it to a folder
                      3. Open Chrome Extensions (`chrome://extensions/`)
                      4. Enable Developer Mode
                      5. Click "Load unpacked" and select the folder

                      ---
                      *By Software for Progress Foundation*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
